#!/bin/sh

set -e

CONFD_OPTIONS=${CONFD_OPTIONS:-"-onetime -backend=env"}

/usr/local/bin/confd -log-level=debug $CONFD_OPTIONS -confdir=/confd

export NODE_PORT="${NODE_PORT:=9000}"

NODE_PORT=${NODE_PORT} http-server /code/public/ -p ${NODE_PORT} --gzip --utc
